# Generated by Django 4.2.2 on 2023-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_sendpost_delete_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=128, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create At'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
    ]
