# Generated by Django 4.2.2 on 2023-06-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
