# Generated by Django 4.2.2 on 2023-06-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_directmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
