# Generated by Django 4.2.2 on 2023-07-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_relationship_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relation', related_query_name='follower_relation', to=settings.AUTH_USER_MODEL, verbose_name='Follower'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relation', related_query_name='following_relation', to=settings.AUTH_USER_MODEL, verbose_name='Following'),
        ),
    ]
