# Generated by Django 4.2.2 on 2023-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_myuser_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
